In [1]:
#!/usr/bin/env python

import sys
import os
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from utils import *
from sklearn.decomposition import TruncatedSVD
from sklearn.decomposition import PCA

sys.path.append(os.path.abspath(os.path.join('..')))

[nltk_data] Downloading package reuters to
[nltk_data]     /Users/bgeilman/nltk_data...
[nltk_data]   Package reuters is already up-to-date!


In [34]:
reuters_corpus = read_corpus()
corpus_words = []
for doc in reuters_corpus:
    for word in doc:
        corpus_words.append(word)       
corpus_words = list(set(corpus_words))
corpus_words.sort()
num_corpus_words = len(corpus_words)
print(num_corpus_words)

8185


In [142]:
word2Ind = {value: index for index, value in enumerate(corpus_words)}
print(word2Ind)

{'"': 0, '"(': 1, '",': 2, '"...': 3, '$': 4, '&': 5, "'": 6, '(': 7, ')': 8, ')"': 9, '),': 10, '),"': 11, ').': 12, ')."': 13, ')...': 14, ')/': 15, ',': 16, ',"': 17, '-': 18, '--': 19, '.': 20, '."': 21, '.(': 22, '.)': 23, '.,': 24, '.,"': 25, '.-': 26, '...': 27, '..."': 28, '...,"': 29, '....': 30, '.....': 31, '......': 32, '.......': 33, '........': 34, '.........': 35, '..........': 36, '...........': 37, '............': 38, '................': 39, './': 40, '.>': 41, '.>,': 42, '/': 43, '0': 44, '00': 45, '000': 46, '001': 47, '01': 48, '011': 49, '014': 50, '015': 51, '02': 52, '020': 53, '023': 54, '0230': 55, '03': 56, '0300': 57, '036': 58, '04': 59, '043': 60, '046': 61, '05': 62, '06': 63, '0600': 64, '063': 65, '0650': 66, '066': 67, '07': 68, '0700': 69, '08': 70, '082': 71, '083': 72, '084': 73, '087': 74, '09': 75, '097': 76, '1': 77, '10': 78, '100': 79, '1002': 80, '101': 81, '102': 82, '103': 83, '104': 84, '105': 85, '106': 86, '108': 87, '109': 88, '10w2': 89,

In [143]:
print(word2Ind['1980s'])

188


In [45]:
reuters_corpus = read_corpus()
print(reuters_corpus[0])

['<START>', 'japan', 'to', 'revise', 'long', '-', 'term', 'energy', 'demand', 'downwards', 'the', 'ministry', 'of', 'international', 'trade', 'and', 'industry', '(', 'miti', ')', 'will', 'revise', 'its', 'long', '-', 'term', 'energy', 'supply', '/', 'demand', 'outlook', 'by', 'august', 'to', 'meet', 'a', 'forecast', 'downtrend', 'in', 'japanese', 'energy', 'demand', ',', 'ministry', 'officials', 'said', '.', 'miti', 'is', 'expected', 'to', 'lower', 'the', 'projection', 'for', 'primary', 'energy', 'supplies', 'in', 'the', 'year', '2000', 'to', '550', 'mln', 'kilolitres', '(', 'kl', ')', 'from', '600', 'mln', ',', 'they', 'said', '.', 'the', 'decision', 'follows', 'the', 'emergence', 'of', 'structural', 'changes', 'in', 'japanese', 'industry', 'following', 'the', 'rise', 'in', 'the', 'value', 'of', 'the', 'yen', 'and', 'a', 'decline', 'in', 'domestic', 'electric', 'power', 'demand', '.', 'miti', 'is', 'planning', 'to', 'work', 'out', 'a', 'revised', 'energy', 'supply', '/', 'demand', 'ou

In [138]:

print(corpus_words.index('barrels'))


1252


In [113]:
window = 4

M = np.zeros((num_corpus_words,num_corpus_words), dtype=int)

for doc in range(0, 3):
    for word in range(0, len(reuters_corpus[doc])):
        #print('Center Word:'+reuters_corpus[doc][word]+" Index:"+str(corpus_words.index(reuters_corpus[doc][word])))
        #print(reuters_corpus[doc][max(0,word-window):word+window+1])
        for window_word in reuters_corpus[doc][max(0,word-window):word+window+1]:
            row = corpus_words.index(reuters_corpus[doc][word])
            column = corpus_words.index(window_word)
            #print('Row: '+str(row))
            #print('Column: '+str(column))
            M[row,column]+=1
        #print(reuters_corpus[i][j])
print(M)
#print(np.max(M))
            

[[10  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [132]:
window = 4

M = np.zeros((num_corpus_words,num_corpus_words), dtype=int)

for doc in range(0, 30):
    for word in range(0, len(reuters_corpus[doc])):
        #print('Center Word:'+reuters_corpus[doc][word]+" Index:"+str(corpus_words.index(reuters_corpus[doc][word])))
        #print(reuters_corpus[doc][max(0,word-window):word+window+1])
        window_range = reuters_corpus[doc][max(0,word-window):word+window+1]
        #print(window_range)
        for window_word in window_range:
            row = corpus_words.index(reuters_corpus[doc][word])
            column = corpus_words.index(window_word)
            #print('Row: '+str(row))
            #print('Column: '+str(column))
            if window_word != reuters_corpus[doc][word]:
                M[row,column]+=1
        #print(reuters_corpus[i][j])
print(M)
print(np.max(M))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
156


In [71]:
testM = np.zeros((4,4), dtype=int)
print(testM)
testM[2,2]=+1
print(testM)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]]


In [141]:
#!/usr/bin/env python

import sys
import os
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from utils import *
from sklearn.decomposition import TruncatedSVD
from sklearn.decomposition import PCA

sys.path.append(os.path.abspath(os.path.join('..')))

def distinct_words(corpus):
    """ Determine a list of distinct words for the corpus.
        Params:
            corpus (list of list of strings): corpus of documents
        Return:
            corpus_words (list of strings): list of distinct words across the corpus, sorted (using python 'sorted' function)
            num_corpus_words (integer): number of distinct words across the corpus
    """
    corpus_words = []
    num_corpus_words = 0

    # ### START CODE HERE ###
    for doc in corpus:
        for word in doc:
            corpus_words.append(word)       
    corpus_words = list(set(corpus_words))
    corpus_words.sort()
    num_corpus_words = len(corpus_words)

    # ### END CODE HERE ###

    return corpus_words, num_corpus_words

def compute_co_occurrence_matrix(corpus, window_size=4):
    """ Compute co-occurrence matrix for the given corpus and window_size (default of 4).

        Note: Each word in a document should be at the center of a window. Words near edges will have a smaller
              number of co-occurring words.

              For example, if we take the document "START All that glitters is not gold END" with window size of 4,
              "All" will co-occur with "START", "that", "glitters", "is", and "not".

        Params:
            corpus (list of list of strings): corpus of documents
            window_size (int): size of context window
        Return:
            M (numpy matrix of shape (number of unique words in the corpus , number of unique words in the corpus)):
                Co-occurrence matrix of word counts.
                The ordering of the words in the rows/columns should be the same as the ordering of the words given by the distinct_words function.
            word2Ind (dict): dictionary that maps word to index (i.e. row/column number) for matrix M.
    """
    words, num_words = distinct_words(corpus)
    M = None
    word2Ind = {}

    # ### START CODE HERE ###
    M = np.zeros((num_words,num_words), dtype=int)

    co_occurrences = {}
    
    for doc in corpus:
        for word in range(0,len(doc)):
            window_range = doc[max(0,word-window_size):word+window_size+1]
            for window_word in window_range:
                row = words.index(doc[word])
                column = words.index(window_word)
                if window_word != doc[word]:
                    M[row,column]+=1
    #print(M)
    #print(np.max(M))

    word2Ind = {value: index for index, value in enumerate(words)}

    # ### END CODE HERE ###

    return M, word2Ind

def reduce_to_k_dim(M, k=2):
    """ Reduce a co-occurrence count matrix of dimensionality (num_corpus_words, num_corpus_words)
        to a matrix of dimensionality (num_corpus_words, k) using the following SVD function from Scikit-Learn:
            - http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html

        Params:
            M (numpy matrix of shape (number of unique words in the corpus , number of unique words in the corpus)): co-occurrence matrix of word counts
            k (int): embedding size of each word after dimension reduction
        Return:
            M_reduced (numpy matrix of shape (number of unique words in the corpus, k)): matrix of k-dimensioal word embeddings.
                    In terms of the SVD from math class, this actually returns U * S
    """
    np.random.seed(4355)
    n_iter = 10     # Use this parameter in your call to `TruncatedSVD`
    M_reduced = None
    print("Running Truncated SVD over %i words..." % (M.shape[0]))

    # ### START CODE HERE ###

    svd = TruncatedSVD(n_components=k, n_iter=n_iter)
    M_reduced = svd.fit_transform(M)

    # ### END CODE HERE ###

    print("Done.")
    return M_reduced

def main():
    matplotlib.use('agg')
    plt.rcParams['figure.figsize'] = [10, 5]

    assert sys.version_info[0] == 3
    assert sys.version_info[1] >= 5

    def plot_embeddings(M_reduced, word2Ind, words, title):

        for word in words:
            idx = word2Ind[word]
            x = M_reduced[idx, 0]
            y = M_reduced[idx, 1]
            plt.scatter(x, y, marker='x', color='red')
            plt.text(x, y, word, fontsize=9)
        plt.savefig(title)

    #Read in the corpus
    reuters_corpus = read_corpus()

    M_co_occurrence, word2Ind_co_occurrence = compute_co_occurrence_matrix(reuters_corpus)
    M_reduced_co_occurrence = reduce_to_k_dim(M_co_occurrence, k=2)
    # Rescale (normalize) the rows to make them each of unit-length
    M_lengths = np.linalg.norm(M_reduced_co_occurrence, axis=1)
    M_normalized = M_reduced_co_occurrence / M_lengths[:, np.newaxis] # broadcasting

    words = ['barrels', 'bpd', 'ecuador', 'energy', 'industry', 'kuwait', 'oil', 'output', 'petroleum', 'venezuela']
    plot_embeddings(M_normalized, word2Ind_co_occurrence, words, 'co_occurrence_embeddings_(soln).png')

if __name__ == "__main__":
    main()


Running Truncated SVD over 8185 words...
Done.
